default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_test_1_development

test:
  <<: *default
  database: rails_test_1_test

production:
  <<: *default
  database: rails_test_1_production
  username: rails_test_1
  password: <%= ENV['RAILS_TEST_1_DATABASE_PASSWORD'] %>
